### ISSUE TITLE
Inline tables nested inside arrays of tables sometimes are not associated with their key

### ISSUE THREAD

**Issue by Lakret** [bitwalker/toml-elixir#37]
An example:

```toml
[[outer]]
inner = { foo = "bar" }
```

is parsed as:

```elixir
%{"outer" => [%{"foo" => "bar"}]}
```

However, adding another `outer` table:

```toml
[[outer]]
inner = { foo = "bar" }

[[outer]]
inner = { foo = "baz" }
```

will produce this:

```elixir
%{
    "outer" => [
        %{"foo" => "bar"}, 
        %{"inner" => %{"foo" => "baz"}}
    ]
}
```

Or, adding another nested inline table:

```toml
[[outer]]
inner = { foo = "bar" }
inner2 = { count = 5 }
```

produces:

```elixir
%{
    "outer" => [
        %{
            "foo" => "bar", 
            "inner2" => %{"count" => 5}
         }
    ]
}
```

I'm open to help with fixing it, but will need some pointers where to look :)
