### ISSUE TITLE
Table redefinition does not produce an error, but instead a malformed document

### ISSUE THREAD

**Issue by ejpcmac** [bitwalker/toml-elixir#9]
Shorter than words, let’s start with an example:

```toml
# config.toml

[my_app."MyApp.Endpoint".url]
scheme = "https"
host = "my-app.com"
port = 443

# Table defined after a subtable
[my_app."MyApp.Endpoint"]
secret_key_base = "secret"
```

When you try to decode this files, it works, but not as one would expect:

```elixir
iex> Toml.decode_file("config.toml")
{:ok,
 %{
   "my_app" => %{
     "MyApp.Endpoint" => %{"secret_key_base" => "secret"},
     "url" => %{"host" => "my-app.com", "port" => 443, "scheme" => "https"}
   }
 }}
```

This means the parser considers the file is the same as:

```toml
[my_app.url]
scheme = "https"
host = "my-app.com"
port = 443

# Table defined after a subtable
[my_app."MyApp.Endpoint"]
secret_key_base = "secret"
```

Which is strange. I’ve had some time wondering why my endpoint wasn’t starting, and hopefully came to this issue. I’ve quickly checked the TOML specifications: I have not seen any statement forbidding this.
